// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: httpx/testdata/test1.proto

package httpx_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Test1) Reset() {
	*x = Test1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpx_testdata_test1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1) ProtoMessage() {}

func (x *Test1) ProtoReflect() protoreflect.Message {
	mi := &file_httpx_testdata_test1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1.ProtoReflect.Descriptor instead.
func (*Test1) Descriptor() ([]byte, []int) {
	return file_httpx_testdata_test1_proto_rawDescGZIP(), []int{0}
}

func (x *Test1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_httpx_testdata_test1_proto protoreflect.FileDescriptor

var file_httpx_testdata_test1_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x74, 0x74, 0x70, 0x78, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x05,
	0x54, 0x65, 0x73, 0x74, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x36,
	0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x78, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x78, 0x3b, 0x68, 0x74, 0x74,
	0x70, 0x78, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_httpx_testdata_test1_proto_rawDescOnce sync.Once
	file_httpx_testdata_test1_proto_rawDescData = file_httpx_testdata_test1_proto_rawDesc
)

func file_httpx_testdata_test1_proto_rawDescGZIP() []byte {
	file_httpx_testdata_test1_proto_rawDescOnce.Do(func() {
		file_httpx_testdata_test1_proto_rawDescData = protoimpl.X.CompressGZIP(file_httpx_testdata_test1_proto_rawDescData)
	})
	return file_httpx_testdata_test1_proto_rawDescData
}

var file_httpx_testdata_test1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_httpx_testdata_test1_proto_goTypes = []interface{}{
	(*Test1)(nil), // 0: Test1
}
var file_httpx_testdata_test1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpx_testdata_test1_proto_init() }
func file_httpx_testdata_test1_proto_init() {
	if File_httpx_testdata_test1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_httpx_testdata_test1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_httpx_testdata_test1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpx_testdata_test1_proto_goTypes,
		DependencyIndexes: file_httpx_testdata_test1_proto_depIdxs,
		MessageInfos:      file_httpx_testdata_test1_proto_msgTypes,
	}.Build()
	File_httpx_testdata_test1_proto = out.File
	file_httpx_testdata_test1_proto_rawDesc = nil
	file_httpx_testdata_test1_proto_goTypes = nil
	file_httpx_testdata_test1_proto_depIdxs = nil
}
