style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/w6d-io/x
options:
  tag_filter_pattern: '^v'
  sort: "date"
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - style
        - chore
        - break
        - BREAKING CHANGE
        - BREAK CHANGE
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Style
      chore: Chore
      break: BREAKING CHANGE
      BREAKING CHANGE: BREAKING CHANGE
      BREAK CHANGE: BREAKING CHANGE
  header:
    pattern: "^(\\w*(?:\\s\\w*)?)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
