name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Get kubebuilder
      uses: RyanSiu1995/kubebuilder-action@v1.1
      with:
        version: 2.3.1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: false # optional (default = false)
        verbose: false # optional (default = false)
